import { IPC_CHANNELS } from '../../shared/constants';

export { IPC_CHANNELS };

export type InvokeChannel =
  | typeof IPC_CHANNELS.DIAL
  | typeof IPC_CHANNELS.ANSWER
  | typeof IPC_CHANNELS.HANGUP
  | typeof IPC_CHANNELS.HOLD
  | typeof IPC_CHANNELS.TRANSFER
  | typeof IPC_CHANNELS.GET_LINES
  | typeof IPC_CHANNELS.GET_CONTACTS
  | typeof IPC_CHANNELS.GET_HISTORY
  | typeof IPC_CHANNELS.GET_VOICEMAILS
  | typeof IPC_CHANNELS.GET_PRESENCE
  | typeof IPC_CHANNELS.GET_BRIDGE_STATE
  | typeof IPC_CHANNELS.GET_SETTINGS
  | typeof IPC_CHANNELS.SET_SETTINGS
  | typeof IPC_CHANNELS.SEND_DTMF
  | typeof IPC_CHANNELS.MUTE
  | typeof IPC_CHANNELS.UNMUTE;

export type EventChannel =
  | typeof IPC_CHANNELS.LINE_STATE_CHANGED
  | typeof IPC_CHANNELS.BRIDGE_STATE_CHANGED
  | typeof IPC_CHANNELS.INCOMING_CALL
  | typeof IPC_CHANNELS.PRESENCE_CHANGED
  | typeof IPC_CHANNELS.CALL_ENDED
  | typeof IPC_CHANNELS.HEARTBEAT;
